export const ACTIVITY_EVENT_TYPE = Object.freeze({
  USER_LOGIN: 'USER_LOGIN',
  ORDER_CREATED: 'ORDER_CREATED',
  ORDER_STATUS_CHANGED: 'ORDER_STATUS_CHANGED',
  ORDER_RISK_CHANGED: 'ORDER_RISK_CHANGED',
  STAGE_STARTED: 'STAGE_STARTED',
  STAGE_COMPLETED: 'STAGE_COMPLETED',
  STAGE_BLOCKED: 'STAGE_BLOCKED',
  STAGE_FAILED: 'STAGE_FAILED',
  RESOURCE_ASSIGNED: 'RESOURCE_ASSIGNED',
  INCIDENT_CREATED: 'INCIDENT_CREATED',
  INCIDENT_RESOLVED: 'INCIDENT_RESOLVED',
  TELEGRAM_ALERT_SENT: 'TELEGRAM_ALERT_SENT',
  TELEGRAM_ALERT_FAILED: 'TELEGRAM_ALERT_FAILED'
})
