export const USER_ROLE = Object.freeze({
  ADMIN: 'ADMIN',
  MANAGER: 'MANAGER',
  OPERATOR: 'OPERATOR'
})

export const RESOURCE_TYPE = Object.freeze({
  KILN: 'KILN',
  DRYER: 'DRYER',
  FORMING: 'FORMING',
  DECORATION: 'DECORATION',
  GLAZING: 'GLAZING',
  QC: 'QC',
  PACKAGING: 'PACKAGING',
  OTHER: 'OTHER'
})

export const RESOURCE_STATUS = Object.freeze({
  AVAILABLE: 'AVAILABLE',
  IN_USE: 'IN_USE',
  MAINTENANCE: 'MAINTENANCE',
  BROKEN: 'BROKEN'
})

export const ORDER_PRIORITY = Object.freeze({
  LOW: 'LOW',
  NORMAL: 'NORMAL',
  HIGH: 'HIGH',
  URGENT: 'URGENT'
})

export const ORDER_STATUS = Object.freeze({
  PENDING: 'PENDING',
  IN_PROGRESS: 'IN_PROGRESS',
  AT_RISK: 'AT_RISK',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED'
})

export const RISK_LEVEL = Object.freeze({
  NONE: 'NONE',
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL'
})

export const ORDER_STAGE_STATUS = Object.freeze({
  WAITING: 'WAITING',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  BLOCKED: 'BLOCKED',
  FAILED: 'FAILED'
})

export const INCIDENT_TYPE = Object.freeze({
  EQUIPMENT_FAILURE: 'EQUIPMENT_FAILURE',
  MATERIAL_SHORTAGE: 'MATERIAL_SHORTAGE',
  QUALITY_ISSUE: 'QUALITY_ISSUE',
  PROCESS_DELAY: 'PROCESS_DELAY',
  ORDER_CHANGE: 'ORDER_CHANGE',
  OTHER: 'OTHER'
})

export const INCIDENT_SEVERITY = Object.freeze({
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL'
})

export const INCIDENT_STATUS = Object.freeze({
  OPEN: 'OPEN',
  RESOLVED: 'RESOLVED'
})

export const ACTIVITY_EVENT_TYPE = Object.freeze({
  USER_LOGIN: 'USER_LOGIN',
  ORDER_CREATED: 'ORDER_CREATED',
  ORDER_STATUS_CHANGED: 'ORDER_STATUS_CHANGED',
  ORDER_RISK_CHANGED: 'ORDER_RISK_CHANGED',
  STAGE_STARTED: 'STAGE_STARTED',
  STAGE_COMPLETED: 'STAGE_COMPLETED',
  STAGE_BLOCKED: 'STAGE_BLOCKED',
  STAGE_FAILED: 'STAGE_FAILED',
  RESOURCE_ASSIGNED: 'RESOURCE_ASSIGNED',
  INCIDENT_CREATED: 'INCIDENT_CREATED',
  INCIDENT_RESOLVED: 'INCIDENT_RESOLVED',
  TELEGRAM_ALERT_SENT: 'TELEGRAM_ALERT_SENT',
  TELEGRAM_ALERT_FAILED: 'TELEGRAM_ALERT_FAILED'
})

export const NOTIFICATION_CHANNEL = Object.freeze({
  TELEGRAM: 'TELEGRAM'
})

export const NOTIFICATION_TYPE = Object.freeze({
  INCIDENT_ALERT: 'INCIDENT_ALERT',
  RISK_ALERT: 'RISK_ALERT',
  STAGE_COMPLETED: 'STAGE_COMPLETED',
  PROGRESS_UPDATE: 'PROGRESS_UPDATE',
  ORDER_COMPLETED: 'ORDER_COMPLETED'
})

export const NOTIFICATION_STATUS = Object.freeze({
  PENDING: 'PENDING',
  SENT: 'SENT',
  FAILED: 'FAILED'
})
