export const INCIDENT_TYPE = Object.freeze({
  EQUIPMENT_FAILURE: 'EQUIPMENT_FAILURE',
  MATERIAL_SHORTAGE: 'MATERIAL_SHORTAGE',
  QUALITY_ISSUE: 'QUALITY_ISSUE',
  PROCESS_DELAY: 'PROCESS_DELAY',
  ORDER_CHANGE: 'ORDER_CHANGE',
  OTHER: 'OTHER'
})

export const INCIDENT_SEVERITY = Object.freeze({
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL'
})

export const INCIDENT_STATUS = Object.freeze({
  OPEN: 'OPEN',
  RESOLVED: 'RESOLVED'
})
