export const NOTIFICATION_CHANNEL = Object.freeze({
  TELEGRAM: 'TELEGRAM'
})

export const NOTIFICATION_TYPE = Object.freeze({
  INCIDENT_ALERT: 'INCIDENT_ALERT',
  RISK_ALERT: 'RISK_ALERT',
  STAGE_COMPLETED: 'STAGE_COMPLETED',
  PROGRESS_UPDATE: 'PROGRESS_UPDATE',
  ORDER_COMPLETED: 'ORDER_COMPLETED'
})

export const NOTIFICATION_STATUS = Object.freeze({
  PENDING: 'PENDING',
  SENT: 'SENT',
  FAILED: 'FAILED'
})
